services:
  web:
    build: .
    links:
      - mysql:mysql
    ports:
      - "8080:8080"
  mysql:
    image: mysql:9
    environment:
      MYSQL_ROOT_PASSWORD: root

  vault:
    image: vault:latest
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      