server:
  port: ${SERVER_PORT:8080}

spring:
  thymeleaf:
    cache: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

logging:
  level:
    root: INFO
    io.infralovers: DEBUG
